CREATE SEQUENCE "WRKCRD"."CC_WRKCRD_RELATION_SEQUENCE" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 24924 CACHE 20 NOORDER NOCYCLE ;

CREATE TABLE "WRKCRD"."CC_WRKCRD_RELATION"
  (
    "ID"         NUMBER NOT NULL ENABLE,
    "TYPE"       VARCHAR2(6 CHAR) NOT NULL ENABLE,
    "SCHOOL"     VARCHAR2(200 BYTE),
    "OCCUPATION" VARCHAR2(200 BYTE),
    "DEGREE"     VARCHAR2(20 BYTE),
    "TO_DATE" DATE,
    "CREATED_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE,
    "CREATED_BY" VARCHAR2(20 BYTE) NOT NULL ENABLE,
    "UPDATE_DATE" DATE,
    "UPDATE_BY"   VARCHAR2(20 BYTE),
    "APPL_ID"     NUMBER NOT NULL ENABLE,
    "GRADE_LEVEL" VARCHAR2(50 BYTE),
    CONSTRAINT "CC_WRKCRD_RELATION_PK" PRIMARY KEY ("ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "CC_DEVELOPMENT" ENABLE,
    CONSTRAINT "CC_WRKCRD_REALTION_APPL_FK" FOREIGN KEY ("APPL_ID") REFERENCES "WRKCRD"."CC_WRKCRD_APPL" ("ID") ENABLE
  )
  SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "CC_DEVELOPMENT" ;
CREATE OR REPLACE TRIGGER "WRKCRD"."CC_WRKCRD_RELATION_ID_TRIGGER" BEFORE
  INSERT ON WRKCRD.CC_WRKCRD_RELATION REFERENCING NEW AS NEW FOR EACH ROW BEGIN
  SELECT CC_WRKCRD_RELATION_SEQUENCE.nextval INTO :NEW.ID FROM dual;
END;
/
ALTER TRIGGER "WRKCRD"."CC_WRKCRD_RELATION_ID_TRIGGER" ENABLE;
/