CREATE TABLE "WRKCRD"."CC_WRKCRD_APPL_STAGE"
  (
    "ID"          VARCHAR2(5 CHAR) NOT NULL ENABLE,
    "DESCRIPTION" VARCHAR2(50 CHAR) NOT NULL ENABLE,
    CONSTRAINT "CC_WRKCRD_APPL_STAGE_PK" PRIMARY KEY ("ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "CC_DEVELOPMENT" ENABLE
  )
  SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "CC_DEVELOPMENT" ;
  
INSERT INTO "WRKCRD"."CC_WRKCRD_APPL_STAGE" (ID, DESCRIPTION) VALUES ('BEGIN', '1st Read');
INSERT INTO "WRKCRD"."CC_WRKCRD_APPL_STAGE" (ID, DESCRIPTION) VALUES ('SWP-E', 'Op Staff Check After Email');
INSERT INTO "WRKCRD"."CC_WRKCRD_APPL_STAGE" (ID, DESCRIPTION) VALUES ('INC-I', 'Incomplete Can Continue Reading');
INSERT INTO "WRKCRD"."CC_WRKCRD_APPL_STAGE" (ID, DESCRIPTION) VALUES ('ASSIG', 'Assigned RDR2');
INSERT INTO "WRKCRD"."CC_WRKCRD_APPL_STAGE" (ID, DESCRIPTION) VALUES ('CHECK', 'Op Staff Check');
INSERT INTO "WRKCRD"."CC_WRKCRD_APPL_STAGE" (ID, DESCRIPTION) VALUES ('COMMI', 'Committee');
INSERT INTO "WRKCRD"."CC_WRKCRD_APPL_STAGE" (ID, DESCRIPTION) VALUES ('END', 'Complete');
INSERT INTO "WRKCRD"."CC_WRKCRD_APPL_STAGE" (ID, DESCRIPTION) VALUES ('ERR-A', 'Data Error - to Assigned RDR2');
INSERT INTO "WRKCRD"."CC_WRKCRD_APPL_STAGE" (ID, DESCRIPTION) VALUES ('ERR-R', 'Data Error - to Rater');
INSERT INTO "WRKCRD"."CC_WRKCRD_APPL_STAGE" (ID, DESCRIPTION) VALUES ('ERR-U', 'Data Error - to Unassigned RDR2');
INSERT INTO "WRKCRD"."CC_WRKCRD_APPL_STAGE" (ID, DESCRIPTION) VALUES ('ERR-B', 'Data Error - Back to Original RDR1');
INSERT INTO "WRKCRD"."CC_WRKCRD_APPL_STAGE" (ID, DESCRIPTION) VALUES ('INCOM', 'Incomplete Missing Materials');
INSERT INTO "WRKCRD"."CC_WRKCRD_APPL_STAGE" (ID, DESCRIPTION) VALUES ('RATE', 'Rater');
INSERT INTO "WRKCRD"."CC_WRKCRD_APPL_STAGE" (ID, DESCRIPTION) VALUES ('SWEEP', 'Sweeper');
INSERT INTO "WRKCRD"."CC_WRKCRD_APPL_STAGE" (ID, DESCRIPTION) VALUES ('UNASI', 'Unasigned RDR2');
INSERT INTO "WRKCRD"."CC_WRKCRD_APPL_STAGE" (ID, DESCRIPTION) VALUES ('INC-R', 'Incomplete - to Rater');
INSERT INTO "WRKCRD"."CC_WRKCRD_APPL_STAGE" (ID, DESCRIPTION) VALUES ('INC-B', 'Incomplete - Back to Original RDR1');
INSERT INTO "WRKCRD"."CC_WRKCRD_APPL_STAGE" (ID, DESCRIPTION) VALUES ('INC-U', 'Incomplete - to Unassigned RDR2');
INSERT INTO "WRKCRD"."CC_WRKCRD_APPL_STAGE" (ID, DESCRIPTION) VALUES ('INC-A', 'Incomplete - to Assigned RDR2');
INSERT INTO "WRKCRD"."CC_WRKCRD_APPL_STAGE" (ID, DESCRIPTION) VALUES ('END-W', 'Requested End');
COMMIT;
/