CREATE SEQUENCE "WRKCRD"."CC_WRKCRD_NOTES_SEQUENCE" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 193792 CACHE 20 NOORDER NOCYCLE ;

CREATE TABLE "WRKCRD"."CC_WRKCRD_NOTES"
  (
    "ID"         NUMBER NOT NULL ENABLE,
    "TYPE"       VARCHAR2(6 CHAR) NOT NULL ENABLE,
    "IDENTIFIER" VARCHAR2(50 BYTE),
    "CREATED_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE,
    "CREATED_BY" VARCHAR2(20 BYTE) NOT NULL ENABLE,
    "UPDATE_DATE" DATE,
    "UPDATE_BY" VARCHAR2(20 BYTE),
    "APPL_ID"   NUMBER NOT NULL ENABLE,
    "CONTENT" CLOB,
    CONSTRAINT "CC_WRKCRD_NOTES_PK" PRIMARY KEY ("ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "CC_DEVELOPMENT" ENABLE,
    CONSTRAINT "CC_WRKCRD_NOTES_APPL_FK" FOREIGN KEY ("APPL_ID") REFERENCES "WRKCRD"."CC_WRKCRD_APPL" ("ID") ENABLE
  )
  SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "CC_DEVELOPMENT" LOB
  (
    "CONTENT"
  )
  STORE AS BASICFILE
  (
    TABLESPACE "CC_DEVELOPMENT" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION NOCACHE LOGGING STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ) ;
CREATE UNIQUE INDEX "WRKCRD"."SYS_IL0000236718C00009$$" ON "WRKCRD"."CC_WRKCRD_NOTES"
  (
    PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "CC_DEVELOPMENT" PARALLEL (DEGREE 0 INSTANCES 0) ;
CREATE UNIQUE INDEX "WRKCRD"."CC_WRKCRD_NOTES_PK" ON "WRKCRD"."CC_WRKCRD_NOTES" ("ID") PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "CC_DEVELOPMENT" ;
  CREATE INDEX "WRKCRD"."CC_WRKCRD_NOTES_TYPE" ON "WRKCRD"."CC_WRKCRD_NOTES"
    (
      "TYPE",
      "IDENTIFIER"
    )
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
    (
      INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
    )
    TABLESPACE "CC_DEVELOPMENT" ;
CREATE OR REPLACE TRIGGER "WRKCRD"."CC_WRKCRD_NOTES_ID_TRIGGER" BEFORE
  INSERT ON WRKCRD.CC_WRKCRD_NOTES REFERENCING NEW AS NEW FOR EACH ROW BEGIN
  SELECT CC_WRKCRD_NOTES_SEQUENCE.nextval INTO :NEW.ID FROM dual;
END;
/
ALTER TRIGGER "WRKCRD"."CC_WRKCRD_NOTES_ID_TRIGGER" ENABLE;
/