CREATE SEQUENCE "WRKCRD"."CC_WRKCRD_EMAIL_SEQUENCE" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 121 CACHE 20 NOORDER NOCYCLE ;

CREATE TABLE "WRKCRD"."CC_WRKCRD_EMAIL"
  (
    "ID"      NUMBER NOT NULL ENABLE,
    "APPL_ID" NUMBER NOT NULL ENABLE,
    "SENDER"  VARCHAR2(20 BYTE) NOT NULL ENABLE,
    "SENT_ON" DATE,
    "SUBJECT" VARCHAR2(500 BYTE),
    "MESSAGE" CLOB,
    "CAN_CONTINUE" NUMBER(*,0) DEFAULT 1 NOT NULL ENABLE,
    CONSTRAINT "CC_WRKCRD_EMAIL_PK" PRIMARY KEY ("ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "CC_DEVELOPMENT" ENABLE,
    CONSTRAINT "FK_WRKCRD_EMAIL_APPL" FOREIGN KEY ("APPL_ID") REFERENCES "WRKCRD"."CC_WRKCRD_APPL" ("ID") ENABLE
  )
  SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "CC_DEVELOPMENT" LOB
  (
    "MESSAGE"
  )
  STORE AS BASICFILE
  (
    TABLESPACE "CC_DEVELOPMENT" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10 NOCACHE LOGGING STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  ) ;
CREATE OR REPLACE TRIGGER "WRKCRD"."CC_WRKCRD_EMAIL_ID_TRIGGER" BEFORE
  INSERT ON CC_WRKCRD_EMAIL REFERENCING NEW AS NEW FOR EACH ROW BEGIN
  SELECT CC_WRKCRD_EMAIL_SEQUENCE.nextval INTO :NEW.ID FROM dual;
END;
/
ALTER TRIGGER "WRKCRD"."CC_WRKCRD_EMAIL_ID_TRIGGER" ENABLE;
/