CREATE TABLE "WRKCRD"."CC_WRKCRD_TEST_TYPE"
  (
    "CODE" VARCHAR2(20 BYTE) NOT NULL ENABLE,
    CONSTRAINT "CC_WRKCRD_TEST_TYPE_PK" PRIMARY KEY ("CODE") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "CC_DEVELOPMENT" ENABLE
  )
  SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "CC_DEVELOPMENT" ;
  
INSERT INTO "WRKCRD"."CC_WRKCRD_TEST_TYPE" (CODE) VALUES ('CH');
INSERT INTO "WRKCRD"."CC_WRKCRD_TEST_TYPE" (CODE) VALUES ('CL');
INSERT INTO "WRKCRD"."CC_WRKCRD_TEST_TYPE" (CODE) VALUES ('EB');
INSERT INTO "WRKCRD"."CC_WRKCRD_TEST_TYPE" (CODE) VALUES ('FL');
INSERT INTO "WRKCRD"."CC_WRKCRD_TEST_TYPE" (CODE) VALUES ('FR');
INSERT INTO "WRKCRD"."CC_WRKCRD_TEST_TYPE" (CODE) VALUES ('GL');
INSERT INTO "WRKCRD"."CC_WRKCRD_TEST_TYPE" (CODE) VALUES ('GM');
INSERT INTO "WRKCRD"."CC_WRKCRD_TEST_TYPE" (CODE) VALUES ('IT');
INSERT INTO "WRKCRD"."CC_WRKCRD_TEST_TYPE" (CODE) VALUES ('JL');
INSERT INTO "WRKCRD"."CC_WRKCRD_TEST_TYPE" (CODE) VALUES ('KL');
INSERT INTO "WRKCRD"."CC_WRKCRD_TEST_TYPE" (CODE) VALUES ('LR');
INSERT INTO "WRKCRD"."CC_WRKCRD_TEST_TYPE" (CODE) VALUES ('LT');
INSERT INTO "WRKCRD"."CC_WRKCRD_TEST_TYPE" (CODE) VALUES ('M1');
INSERT INTO "WRKCRD"."CC_WRKCRD_TEST_TYPE" (CODE) VALUES ('M2');
INSERT INTO "WRKCRD"."CC_WRKCRD_TEST_TYPE" (CODE) VALUES ('MB');
INSERT INTO "WRKCRD"."CC_WRKCRD_TEST_TYPE" (CODE) VALUES ('MH');
INSERT INTO "WRKCRD"."CC_WRKCRD_TEST_TYPE" (CODE) VALUES ('PH');
INSERT INTO "WRKCRD"."CC_WRKCRD_TEST_TYPE" (CODE) VALUES ('SL');
INSERT INTO "WRKCRD"."CC_WRKCRD_TEST_TYPE" (CODE) VALUES ('SP');
INSERT INTO "WRKCRD"."CC_WRKCRD_TEST_TYPE" (CODE) VALUES ('UH');
INSERT INTO "WRKCRD"."CC_WRKCRD_TEST_TYPE" (CODE) VALUES ('WH');
INSERT INTO "WRKCRD"."CC_WRKCRD_TEST_TYPE" (CODE) VALUES ('SATM');
INSERT INTO "WRKCRD"."CC_WRKCRD_TEST_TYPE" (CODE) VALUES ('SATR');
INSERT INTO "WRKCRD"."CC_WRKCRD_TEST_TYPE" (CODE) VALUES ('SATW');
INSERT INTO "WRKCRD"."CC_WRKCRD_TEST_TYPE" (CODE) VALUES ('AHI');
INSERT INTO "WRKCRD"."CC_WRKCRD_TEST_TYPE" (CODE) VALUES ('AR2');
INSERT INTO "WRKCRD"."CC_WRKCRD_TEST_TYPE" (CODE) VALUES ('AR3');
INSERT INTO "WRKCRD"."CC_WRKCRD_TEST_TYPE" (CODE) VALUES ('ART');
INSERT INTO "WRKCRD"."CC_WRKCRD_TEST_TYPE" (CODE) VALUES ('BSC');
INSERT INTO "WRKCRD"."CC_WRKCRD_TEST_TYPE" (CODE) VALUES ('CAB');
INSERT INTO "WRKCRD"."CC_WRKCRD_TEST_TYPE" (CODE) VALUES ('CBC');
INSERT INTO "WRKCRD"."CC_WRKCRD_TEST_TYPE" (CODE) VALUES ('CHM');
INSERT INTO "WRKCRD"."CC_WRKCRD_TEST_TYPE" (CODE) VALUES ('CLL');
INSERT INTO "WRKCRD"."CC_WRKCRD_TEST_TYPE" (CODE) VALUES ('COA');
INSERT INTO "WRKCRD"."CC_WRKCRD_TEST_TYPE" (CODE) VALUES ('COM');
INSERT INTO "WRKCRD"."CC_WRKCRD_TEST_TYPE" (CODE) VALUES ('ENG');
INSERT INTO "WRKCRD"."CC_WRKCRD_TEST_TYPE" (CODE) VALUES ('ENL');
INSERT INTO "WRKCRD"."CC_WRKCRD_TEST_TYPE" (CODE) VALUES ('ENS');
INSERT INTO "WRKCRD"."CC_WRKCRD_TEST_TYPE" (CODE) VALUES ('EUH');
INSERT INTO "WRKCRD"."CC_WRKCRD_TEST_TYPE" (CODE) VALUES ('FRH');
INSERT INTO "WRKCRD"."CC_WRKCRD_TEST_TYPE" (CODE) VALUES ('FRL');
INSERT INTO "WRKCRD"."CC_WRKCRD_TEST_TYPE" (CODE) VALUES ('GEO');
INSERT INTO "WRKCRD"."CC_WRKCRD_TEST_TYPE" (CODE) VALUES ('GER');
INSERT INTO "WRKCRD"."CC_WRKCRD_TEST_TYPE" (CODE) VALUES ('GOV');
INSERT INTO "WRKCRD"."CC_WRKCRD_TEST_TYPE" (CODE) VALUES ('GUS');
INSERT INTO "WRKCRD"."CC_WRKCRD_TEST_TYPE" (CODE) VALUES ('ITS');
INSERT INTO "WRKCRD"."CC_WRKCRD_TEST_TYPE" (CODE) VALUES ('JLL');
INSERT INTO "WRKCRD"."CC_WRKCRD_TEST_TYPE" (CODE) VALUES ('LAL');
INSERT INTO "WRKCRD"."CC_WRKCRD_TEST_TYPE" (CODE) VALUES ('LAT');
INSERT INTO "WRKCRD"."CC_WRKCRD_TEST_TYPE" (CODE) VALUES ('MAC');
INSERT INTO "WRKCRD"."CC_WRKCRD_TEST_TYPE" (CODE) VALUES ('MIC');
INSERT INTO "WRKCRD"."CC_WRKCRD_TEST_TYPE" (CODE) VALUES ('MUS');
INSERT INTO "WRKCRD"."CC_WRKCRD_TEST_TYPE" (CODE) VALUES ('PHE');
INSERT INTO "WRKCRD"."CC_WRKCRD_TEST_TYPE" (CODE) VALUES ('PHM');
INSERT INTO "WRKCRD"."CC_WRKCRD_TEST_TYPE" (CODE) VALUES ('PHY');
INSERT INTO "WRKCRD"."CC_WRKCRD_TEST_TYPE" (CODE) VALUES ('PSY');
INSERT INTO "WRKCRD"."CC_WRKCRD_TEST_TYPE" (CODE) VALUES ('SPA');
INSERT INTO "WRKCRD"."CC_WRKCRD_TEST_TYPE" (CODE) VALUES ('SPL');
INSERT INTO "WRKCRD"."CC_WRKCRD_TEST_TYPE" (CODE) VALUES ('STA');
INSERT INTO "WRKCRD"."CC_WRKCRD_TEST_TYPE" (CODE) VALUES ('USH');
INSERT INTO "WRKCRD"."CC_WRKCRD_TEST_TYPE" (CODE) VALUES ('WHI');
INSERT INTO "WRKCRD"."CC_WRKCRD_TEST_TYPE" (CODE) VALUES ('IELT');
INSERT INTO "WRKCRD"."CC_WRKCRD_TEST_TYPE" (CODE) VALUES ('TFLC');
INSERT INTO "WRKCRD"."CC_WRKCRD_TEST_TYPE" (CODE) VALUES ('TFLI');
INSERT INTO "WRKCRD"."CC_WRKCRD_TEST_TYPE" (CODE) VALUES ('TFLP');
INSERT INTO "WRKCRD"."CC_WRKCRD_TEST_TYPE" (CODE) VALUES ('ACT');
INSERT INTO "WRKCRD"."CC_WRKCRD_TEST_TYPE" (CODE) VALUES ('ACTE');
INSERT INTO "WRKCRD"."CC_WRKCRD_TEST_TYPE" (CODE) VALUES ('ACTM');
INSERT INTO "WRKCRD"."CC_WRKCRD_TEST_TYPE" (CODE) VALUES ('ACTR');
INSERT INTO "WRKCRD"."CC_WRKCRD_TEST_TYPE" (CODE) VALUES ('ACTS');
COMMIT;
/