CREATE TABLE "WRKCRD"."CC_WRKCRD_YCC"
  (
    "CODE"        VARCHAR2(20 BYTE) NOT NULL ENABLE,
    "DESCRIPTION" VARCHAR2(50 BYTE) NOT NULL ENABLE
  )
  SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "CC_DEVELOPMENT" ;
  
INSERT INTO "WRKCRD"."CC_WRKCRD_YCC" (CODE, DESCRIPTION) VALUES ('ACAT', 'Arts and Tech');
INSERT INTO "WRKCRD"."CC_WRKCRD_YCC" (CODE, DESCRIPTION) VALUES ('ACCBES', 'CCBES');
INSERT INTO "WRKCRD"."CC_WRKCRD_YCC" (CODE, DESCRIPTION) VALUES ('ACCSRE', 'CCRSE');
INSERT INTO "WRKCRD"."CC_WRKCRD_YCC" (CODE, DESCRIPTION) VALUES ('ACISLA', 'CISLA');
INSERT INTO "WRKCRD"."CC_WRKCRD_YCC" (CODE, DESCRIPTION) VALUES ('AHOLLR', 'Holleran-PICA');
COMMIT;
/