CREATE TABLE "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER"
  (
    "ID"          VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "TYPE"        VARCHAR2(10 BYTE) NOT NULL ENABLE,
    "DESCRIPTION" VARCHAR2(50 BYTE) NOT NULL ENABLE,
    CONSTRAINT "CC_WRKCRD_NOTE_IDENTIFIER_PK" PRIMARY KEY ("ID", "TYPE") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "CC_DEVELOPMENT" ENABLE
  )
  SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "CC_DEVELOPMENT" ;
  
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('ARC', 'ACT', 'Archery');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('ART', 'ACT', 'Art');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('BAD', 'ACT', 'Badminton');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('BSB', 'ACT', 'Baseball');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('BSK', 'ACT', 'Basketball');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('BWL', 'ACT', 'Bowling');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('BOX', 'ACT', 'Boxing');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('CHR', 'ACT', 'Cheerleading');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('INT', 'ACTClub sports');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('CMP', 'ACT', 'Computers');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('CKT', 'ACT', 'Cricket');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('XCT', 'ACT', 'Cross country');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('DAN', 'ACT', 'Dance');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('DEB', 'ACT', 'Debate/speech');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('DIV', 'ACT', 'Diving');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('ENV', 'ACT', 'Envi club');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('EQU', 'ACT', 'Equestrian');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('FEX', 'ACT', 'Exchange to:');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('FRS', 'ACT', 'Family responsibilities');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('FEN', 'ACT', 'Fencing');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('FLD', 'ACT', 'Field hockey');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('FLG', 'ACT', 'Foreign lang club');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('FFB', 'ACT', 'Flag football');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('FOT', 'ACT', 'Football');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('GOL', 'ACT', 'Golf');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('GYM', 'ACT', 'Gymnastics');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('HND', 'ACT', 'Handball');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('ICE', 'ACT', 'Ice hockey');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('JRN', 'ACT', 'Journalism');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('JDO', 'ACT', 'Judo');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('LAX', 'ACT', 'Lacrosse');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('LGB', 'ACT', 'LGBTQ');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('INS', 'ACT', 'MUS: instrument');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('VOC', 'ACT', 'MUS: voice');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('JRO', 'ACT', 'R.O.T.C.');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('RAQ', 'ACT', 'Racquetball');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('REL', 'ACT', 'Religious yth grp');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('RFL', 'ACT', 'Rifle');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('RDO', 'ACT', 'Rodeo');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('ROW', 'ACT', 'Rowing');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('RUG', 'ACT', 'Rugby');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('SAL', 'ACT', 'Sailing');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('SCI', 'ACT', 'Sci/math club');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('STU', 'ACT', 'SGA');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('SKI', 'ACT', 'Skiing (nordic / downhill)');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('SDV', 'ACT', 'Skin diving');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('SOC', 'ACT', 'Soccer');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('SOF', 'ACT', 'Softball');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('SCH', 'ACT', 'Spirit club');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('SQU', 'ACT', 'Squash');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('SWM', 'ACT', 'Swimming');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('SSW', 'ACT', 'Sync swimming');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('TTN', 'ACT', 'Table tennis');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('TEN', 'ACT', 'Tennis');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('THE', 'ACT', 'Theater');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('IND', 'ACT', 'Track (in)');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('OUT', 'ACT', 'Track (out)');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('TAF', 'ACT', 'Track-Field');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('TRI', 'ACT', 'Triathalon');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('COM', 'ACT', 'Vol work');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('VOL', 'ACT', 'Volleyball');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('WPO', 'ACT', 'Water polo');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('WGT', 'ACT', 'Weightlifting');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('WRK', 'ACT', 'Work');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('WRE', 'ACT', 'Wrestling');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('ADV', 'ACT', 'Advocacy grp');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('AMN', 'ACT', 'Amnesty intl');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('BKA', 'ACT', 'Book award:');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('BKC', 'ACT', 'Book award: CC');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('CMC', 'ACT', 'Camp cslr / CIT');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('CYG', 'ACT', 'Church yth grp');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('CSS', 'ACT', 'CSSSA (CA Sum Sch for Arts)');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('CTY', 'ACT', 'Ctr talented yth (Johns Hop)');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('FIG', 'ACT', 'Figure skating');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('FRN', 'ACT', 'French NHS');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('GSA', 'ACT', 'GSA');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('HAB', 'ACT', 'Habitat for humanity');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('JEW', 'ACT', 'Jewish yth grp');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('JSA', 'ACT', 'Junior statesmen america');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('LIF', 'ACT', 'Life guard');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('MKT', 'ACT', 'Mock trial');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('MUN', 'ACT', 'MUN');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('MCP', 'ACT', 'MUS: a cappella');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('MBA', 'ACT', 'MUS: band');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('MCH', 'ACT', 'MUS: choir / vocal grp');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('MOR', 'ACT', 'MUS: orchestra');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('MRB', 'ACT', 'MUS: rock band');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('NAN', 'ACT', 'NaNoWriMo (natl novel wrtg month)');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('NMC', 'ACT', 'Natl merit commended');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('NMF', 'ACT', 'Natl merit finalist');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('NMS', 'ACT', 'Natl merit semi-fin');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('NYL', 'ACT', 'Natl yth leader forum');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('NEW', 'ACT', 'Newspaper');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('OCL', 'ACT', 'Outing cl');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('OTB', 'ACT', 'Outward bound');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('PER', 'ACT', 'Peer mentor');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('PRE', 'ACT', 'Prefect: dorm');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('PRS', 'ACT', 'Prefect: school');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('SCT', 'ACT', 'Scouting');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('SOR', 'ACT', 'SOC organization');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('SPN', 'ACT', 'Spanish NHS');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('TOU', 'ACT', 'Tour guide');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('TUT', 'ACT', 'Tutor');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('YEA', 'ACT', 'Yearbook');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('YTH', 'ACT', 'Youth in govt');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('Math', 'TR', 'Math');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('Eng', 'TR', 'English');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('F', 'LANG', 'First');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('H', 'LANG', 'at Home');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('F,H', 'LANG', 'First & at Home');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('Science', 'TR', 'Science');
INSERT INTO "WRKCRD"."CC_WRKCRD_NOTE_IDENTIFIER" (ID, TYPE, DESCRIPTION) VALUES ('Other', 'TR', 'Other');
COMMIT;
/