CREATE TABLE "WRKCRD"."CC_WRKCRD_TERM_ADMT_DEFS"
  (
    "TERM" VARCHAR2(6 BYTE) NOT NULL ENABLE,
    "ADMT" VARCHAR2(5 BYTE) NOT NULL ENABLE,
    "START_DATE" DATE NOT NULL ENABLE,
    "END_DATE" DATE NOT NULL ENABLE,
    CONSTRAINT "CC_WRKCRD_TERM_ADMT_DEFS_PK" PRIMARY KEY ("TERM", "ADMT") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "CC_DEVELOPMENT" ENABLE
  )
  SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "CC_DEVELOPMENT" ;
  
INSERT INTO "WRKCRD"."CC_WRKCRD_TERM_ADMT_DEFS" (TERM, ADMT, START_DATE, END_DATE) VALUES ('201110', 'TR', '15-NOV-11', '15-DEC-11');
INSERT INTO "WRKCRD"."CC_WRKCRD_TERM_ADMT_DEFS" (TERM, ADMT, START_DATE, END_DATE) VALUES ('201290', 'E1', '15-NOV-11', '15-DEC-11');
INSERT INTO "WRKCRD"."CC_WRKCRD_TERM_ADMT_DEFS" (TERM, ADMT, START_DATE, END_DATE) VALUES ('201290', 'E2', '01-JAN-12', '01-APR-12');
INSERT INTO "WRKCRD"."CC_WRKCRD_TERM_ADMT_DEFS" (TERM, ADMT, START_DATE, END_DATE) VALUES ('201290', 'FR', '01-JAN-12', '01-APR-12');
INSERT INTO "WRKCRD"."CC_WRKCRD_TERM_ADMT_DEFS" (TERM, ADMT, START_DATE, END_DATE) VALUES ('201290', 'RT', '20-MAR-12', '01-MAY-12');
INSERT INTO "WRKCRD"."CC_WRKCRD_TERM_ADMT_DEFS" (TERM, ADMT, START_DATE, END_DATE) VALUES ('201290', 'TR', '20-MAR-12', '01-MAY-12');
INSERT INTO "WRKCRD"."CC_WRKCRD_TERM_ADMT_DEFS" (TERM, ADMT, START_DATE, END_DATE) VALUES ('201310', 'FR', '15-OCT-12', '15-DEC-12');
INSERT INTO "WRKCRD"."CC_WRKCRD_TERM_ADMT_DEFS" (TERM, ADMT, START_DATE, END_DATE) VALUES ('201310', 'RT', '15-OCT-12', '15-DEC-12');
INSERT INTO "WRKCRD"."CC_WRKCRD_TERM_ADMT_DEFS" (TERM, ADMT, START_DATE, END_DATE) VALUES ('201310', 'TR', '15-OCT-12', '15-DEC-12');
INSERT INTO "WRKCRD"."CC_WRKCRD_TERM_ADMT_DEFS" (TERM, ADMT, START_DATE, END_DATE) VALUES ('201390', 'E1', '01-NOV-12', '15-DEC-12');
INSERT INTO "WRKCRD"."CC_WRKCRD_TERM_ADMT_DEFS" (TERM, ADMT, START_DATE, END_DATE) VALUES ('201390', 'E2', '15-DEC-12', '01-APR-13');
INSERT INTO "WRKCRD"."CC_WRKCRD_TERM_ADMT_DEFS" (TERM, ADMT, START_DATE, END_DATE) VALUES ('201390', 'FR', '15-DEC-12', '01-APR-13');
INSERT INTO "WRKCRD"."CC_WRKCRD_TERM_ADMT_DEFS" (TERM, ADMT, START_DATE, END_DATE) VALUES ('201390', 'RT', '20-MAR-13', '01-MAY-13');
INSERT INTO "WRKCRD"."CC_WRKCRD_TERM_ADMT_DEFS" (TERM, ADMT, START_DATE, END_DATE) VALUES ('201390', 'TR', '20-MAR-13', '01-MAY-13');
COMMIT;
/